name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Yarn Berry
        run: npm install --global yarn@berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build
